export interface RegisterOptions {
  /**
   * 支付宝开放平台分配的 appId
   * The appId assigned by Alipay Open Platform
   */
  appId: string;
}

export interface PayOptions {
  /**
   * 服务端生成的订单信息字符串
   * The order info string generated by the server
   */
  orderInfo: string;
}

export interface PayResult {
  /**
   * 结果状态码
   * Result status code
   *
   * - 9000: 订单支付成功 / Payment successful
   * - 8000: 正在处理中，支付结果未知（有可能已经支付成功），请查询商家订单列表中订单的支付状态 / Processing, result unknown (may have succeeded), check order status
   * - 4000: 订单支付失败 / Payment failed
   * - 5000: 重复请求 / Duplicate request
   * - 6001: 用户中途取消 / User cancelled
   * - 6002: 网络连接出错 / Network error
   * - 6004: 支付结果未知（有可能已经支付成功），请查询商家订单列表中订单的支付状态 / Result unknown (may have succeeded), check order status
   * - 其它: 其它支付错误 / Other payment errors
   */
  resultStatus: string;
  /**
   * 结果描述
   * Result description
   */
  result: string;
  /**
   * 结果备注
   * Result memo
   */
  memo: string;
}

export interface AlipayPlugin {
  /**
   * 注册支付宝 appId，建议在应用启动时调用，用于防黑产安全逻辑和优化支付体验
   * Register Alipay appId. Recommended to call at app startup for anti-fraud security and payment experience optimization
   */
  register(options: RegisterOptions): Promise<void>;

  /**
   * 发起支付宝支付
   * Initiate Alipay payment
   */
  pay(options: PayOptions): Promise<PayResult>;
}
