package top.fosky.plugins.alipay

import android.app.Activity
import com.alipay.sdk.app.PayTask
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

class Alipay {
    /**
     * 发起支付宝支付
     * Initiate Alipay payment
     *
     * @param activity 当前 Activity / Current Activity
     * @param orderInfo 服务端生成的订单信息字符串 / Order info string generated by server
     * @return 支付结果 Map，包含 resultStatus, result, memo / Payment result Map containing resultStatus, result, memo
     */
    suspend fun pay(activity: Activity, orderInfo: String): Map<String, String> {
        return withContext(Dispatchers.IO) {
            val payTask = PayTask(activity)
            payTask.payV2(orderInfo, true)
        }
    }
}
